-- ============================================================
-- AssamStudentHub Database Initialization Schema
-- Run this entire script in your Supabase SQL Editor to set up
-- all tables, indexes, triggers, search functions, RLS policies,
-- and seed data from scratch.
-- ============================================================

-- 1. Enable Database Extensions
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Create Institutions Table
CREATE TABLE IF NOT EXISTS institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    website TEXT,
    location TEXT,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Notices Table
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    source TEXT NOT NULL,
    source_url TEXT NOT NULL,
    category TEXT NOT NULL,
    content_type TEXT,
    institution TEXT NOT NULL,
    institution_slug TEXT,
    posted_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    tags TEXT[] DEFAULT '{}',
    slug TEXT NOT NULL UNIQUE,
    raw_html TEXT,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    content_hash TEXT NOT NULL UNIQUE,
    attachment_url TEXT,
    institution_id BIGINT REFERENCES institutions(id) ON DELETE SET NULL,
    is_official BOOLEAN DEFAULT true NOT NULL,
    merged_into_notice_id BIGINT REFERENCES notices(id) ON DELETE SET NULL,
    canonical_url TEXT,
    removed_at TIMESTAMP WITH TIME ZONE,
    reliability_score INTEGER DEFAULT 10,
    scraper_name TEXT,
    search_vector tsvector
);

-- 4. Create Scraper Runs Table
CREATE TABLE IF NOT EXISTS scraper_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scraper_name TEXT NOT NULL,
    status TEXT NOT NULL, -- 'running', 'completed', 'failed'
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    items_scraped INTEGER DEFAULT 0,
    items_inserted INTEGER DEFAULT 0,
    items_updated INTEGER DEFAULT 0,
    errors TEXT[] DEFAULT '{}',
    duration_seconds INTEGER,
    traceback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Saved Notices Table
CREATE TABLE IF NOT EXISTS saved_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    notice_id BIGINT NOT NULL REFERENCES notices(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, notice_id)
);

-- 6. Create Search Logs Table
CREATE TABLE IF NOT EXISTS search_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT NOT NULL,
    results_count INTEGER DEFAULT 0 NOT NULL,
    search_type TEXT DEFAULT 'fts', -- 'fts' | 'fuzzy' | 'ilike'
    search_duration_ms INTEGER,
    category TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Saved Searches Table
CREATE TABLE IF NOT EXISTS saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    query TEXT NOT NULL,
    category TEXT,
    label TEXT,
    notify_enabled BOOLEAN DEFAULT false NOT NULL,
    last_checked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, query, category)
);

-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_notices_source_url ON notices(source_url);
CREATE INDEX IF NOT EXISTS idx_notices_slug ON notices(slug);
CREATE INDEX IF NOT EXISTS idx_notices_category ON notices(category);
CREATE INDEX IF NOT EXISTS idx_notices_institution ON notices(institution);
CREATE INDEX IF NOT EXISTS idx_notices_is_active ON notices(is_active);
CREATE INDEX IF NOT EXISTS idx_notices_content_type ON notices(content_type);
CREATE INDEX IF NOT EXISTS idx_notices_institution_slug ON notices(institution_slug);
CREATE INDEX IF NOT EXISTS idx_notices_institution_id ON notices(institution_id);
CREATE INDEX IF NOT EXISTS idx_notices_content_hash ON notices(content_hash);
CREATE INDEX IF NOT EXISTS idx_notices_reliability_score ON notices(reliability_score);
CREATE INDEX IF NOT EXISTS idx_notices_is_official ON notices(is_official);
CREATE INDEX IF NOT EXISTS idx_notices_merged_into_notice_id ON notices(merged_into_notice_id);

CREATE INDEX IF NOT EXISTS idx_scraper_runs_name ON scraper_runs(scraper_name);
CREATE INDEX IF NOT EXISTS idx_scraper_runs_status ON scraper_runs(status);

CREATE INDEX IF NOT EXISTS idx_saved_notices_user_id ON saved_notices(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_notices_notice_id ON saved_notices(notice_id);

CREATE INDEX IF NOT EXISTS idx_search_logs_query ON search_logs(query);
CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON search_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_logs_user_id ON search_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_saved_searches_user_id ON saved_searches(user_id);

-- GIN index for fast Full-Text Search
CREATE INDEX IF NOT EXISTS idx_notices_search_vector ON notices USING GIN(search_vector);
-- Trigram index for fuzzy typo-tolerant queries
CREATE INDEX IF NOT EXISTS idx_notices_title_trgm ON notices USING GIN(title gin_trgm_ops);

-- ============================================================
-- FUNCTIONS AND TRIGGERS
-- ============================================================

-- Function to update the search_vector on insert/update
CREATE OR REPLACE FUNCTION notices_search_vector_update()
RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.institution, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.category, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(NEW.description, '') || ' ' || coalesce(NEW.source, '')), 'D');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS notices_search_vector_trigger ON notices;
CREATE TRIGGER notices_search_vector_trigger
  BEFORE INSERT OR UPDATE ON notices
  FOR EACH ROW EXECUTE FUNCTION notices_search_vector_update();

-- Ranked Full-Text Search RPC Function
CREATE OR REPLACE FUNCTION search_notices(
  search_query  TEXT,
  p_category    TEXT    DEFAULT NULL,
  p_page        INT     DEFAULT 1,
  p_page_size   INT     DEFAULT 6
)
RETURNS TABLE (
  id                    INT8,
  title                 TEXT,
  slug                  TEXT,
  description           TEXT,
  category              TEXT,
  content_type          TEXT,
  institution           TEXT,
  institution_slug      TEXT,
  source                TEXT,
  source_url            TEXT,
  posted_at             TIMESTAMPTZ,
  scraped_at            TIMESTAMPTZ,
  created_at            TIMESTAMPTZ,
  updated_at            TEXT,
  tags                  TEXT[],
  attachment_url        TEXT,
  institution_id        INT8,
  is_active             BOOLEAN,
  is_official           BOOLEAN,
  merged_into_notice_id INT8,
  content_hash          TEXT,
  scraper_name          TEXT,
  search_rank           FLOAT4
) AS $$
DECLARE
  ts_query   tsquery;
  offset_val INT := (p_page - 1) * p_page_size;
END;
$$ LANGUAGE plpgsql STABLE;

-- Overwrite with drop-first pattern to prevent parameter conflicts
DROP FUNCTION IF EXISTS search_notices(TEXT, TEXT, INTEGER, INTEGER);
CREATE OR REPLACE FUNCTION search_notices(
  search_query  TEXT,
  p_category    TEXT    DEFAULT NULL,
  p_page        INT     DEFAULT 1,
  p_page_size   INT     DEFAULT 6
)
RETURNS TABLE (
  id                    INT8,
  title                 TEXT,
  slug                  TEXT,
  description           TEXT,
  category              TEXT,
  content_type          TEXT,
  institution           TEXT,
  institution_slug      TEXT,
  source                TEXT,
  source_url            TEXT,
  posted_at             TIMESTAMPTZ,
  scraped_at            TIMESTAMPTZ,
  created_at            TIMESTAMPTZ,
  updated_at            TEXT,
  tags                  TEXT[],
  attachment_url        TEXT,
  institution_id        INT8,
  is_active             BOOLEAN,
  is_official           BOOLEAN,
  merged_into_notice_id INT8,
  content_hash          TEXT,
  scraper_name          TEXT,
  search_rank           FLOAT4
) AS $$
DECLARE
  ts_query   tsquery;
  offset_val INT := (p_page - 1) * p_page_size;
BEGIN
  ts_query := plainto_tsquery('english', search_query);

  RETURN QUERY
  SELECT
    n.id,
    n.title,
    n.slug,
    n.description,
    n.category,
    n.content_type,
    n.institution,
    n.institution_slug,
    n.source,
    n.source_url,
    n.posted_at,
    n.scraped_at,
    n.created_at,
    n.updated_at::TEXT,
    n.tags,
    n.attachment_url,
    n.institution_id,
    n.is_active,
    n.is_official,
    n.merged_into_notice_id,
    n.content_hash,
    n.scraper_name,
    (
      ts_rank_cd(n.search_vector, ts_query) *
      (1.0 / (1.0 + EXTRACT(EPOCH FROM (now() - coalesce(n.posted_at, n.created_at))) / 86400.0 / 30.0))
    )::FLOAT4 AS search_rank
  FROM notices n
  WHERE
    n.is_active = true
    AND n.merged_into_notice_id IS NULL
    AND n.search_vector @@ ts_query
    AND (p_category IS NULL OR lower(n.category) = lower(p_category))
  ORDER BY search_rank DESC
  LIMIT p_page_size
  OFFSET offset_val;
END;
$$ LANGUAGE plpgsql STABLE;

-- Fuzzy Search RPC Function
DROP FUNCTION IF EXISTS fuzzy_search_notices(TEXT, TEXT, FLOAT, INTEGER);
CREATE OR REPLACE FUNCTION fuzzy_search_notices(
  search_query  TEXT,
  p_category    TEXT    DEFAULT NULL,
  p_threshold   FLOAT   DEFAULT 0.25,
  p_page_size   INT     DEFAULT 6
)
RETURNS TABLE (
  id                    INT8,
  title                 TEXT,
  slug                  TEXT,
  description           TEXT,
  category              TEXT,
  content_type          TEXT,
  institution           TEXT,
  institution_slug      TEXT,
  source                TEXT,
  source_url            TEXT,
  posted_at             TIMESTAMPTZ,
  scraped_at            TIMESTAMPTZ,
  created_at            TIMESTAMPTZ,
  updated_at            TEXT,
  tags                  TEXT[],
  attachment_url        TEXT,
  institution_id        INT8,
  is_active             BOOLEAN,
  is_official           BOOLEAN,
  merged_into_notice_id INT8,
  content_hash          TEXT,
  scraper_name          TEXT,
  search_rank           FLOAT4
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    n.id,
    n.title,
    n.slug,
    n.description,
    n.category,
    n.content_type,
    n.institution,
    n.institution_slug,
    n.source,
    n.source_url,
    n.posted_at,
    n.scraped_at,
    n.created_at,
    n.updated_at::TEXT,
    n.tags,
    n.attachment_url,
    n.institution_id,
    n.is_active,
    n.is_official,
    n.merged_into_notice_id,
    n.content_hash,
    n.scraper_name,
    word_similarity(search_query, n.title)::FLOAT4 AS search_rank
  FROM notices n
  WHERE
    n.is_active = true
    AND n.merged_into_notice_id IS NULL
    AND word_similarity(search_query, n.title) > p_threshold
    AND (p_category IS NULL OR lower(n.category) = lower(p_category))
  ORDER BY search_rank DESC, n.posted_at DESC NULLS LAST
  LIMIT p_page_size;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================================
-- ROW LEVEL SECURITY AND POLICIES
-- ============================================================

ALTER TABLE search_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow insert for all" ON search_logs;
CREATE POLICY "Allow insert for all" ON search_logs FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Users read own logs" ON search_logs;
CREATE POLICY "Users read own logs" ON search_logs FOR SELECT USING (user_id = auth.uid() OR user_id IS NULL);

ALTER TABLE saved_searches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own saved searches" ON saved_searches;
CREATE POLICY "Users manage own saved searches" ON saved_searches
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- SEED DATA: ALL INSTITUTIONS
-- ============================================================

INSERT INTO institutions (name, slug, description, website, location)
VALUES
    (
        'Assam Public Service Commission', 
        'assam-public-service-commission', 
        'The premier recruitment body of the Government of Assam for selecting candidates for state civil services and other administrative posts.', 
        'https://apsc.nic.in', 
        'Khanapara, Guwahati, Assam'
    ),
    (
        'State Level Police Recruitment Board', 
        'state-level-police-recruitment-board', 
        'The board responsible for conducting recruitment examinations for various posts in the Assam Police and other allied departments.', 
        'https://slprbassam.in', 
        'Guwahati, Assam'
    ),
    (
        'Tezpur University', 
        'tezpur-university', 
        'A Central University located in Tezpur, Assam, established by an Act of Parliament in 1994.', 
        'https://www.tezu.ernet.in', 
        'Tezpur, Sonitpur, Assam'
    ),
    (
        'Bodoland University', 
        'bodoland-university', 
        'A state university located in Kokrajhar, Assam, catering to the higher education needs of the Bodoland Territorial Region.', 
        'https://www.buniv.edu.in', 
        'Kokrajhar, Assam'
    ),
    (
        'Mangaldai College', 
        'mangaldai-college', 
        'A premier co-educational higher education institution located in Mangaldai, Darrang, Assam.', 
        'https://mangaldaicollege.org', 
        'Mangaldai, Darrang, Assam'
    ),
    (
        'National Health Mission, Assam', 
        'nhm-assam', 
        'The state branch of the National Health Mission, responsible for health systems reinforcement and recruitment in Assam.', 
        'https://nhm.assam.gov.in', 
        'Guwahati, Assam'
    ),
    (
        'Assam Engineering Service Recruitment Board', 
        'aesrb', 
        'The board responsible for conducting recruitment examinations for various engineering and technical academic posts in Assam.', 
        'https://www.aesrb.in', 
        'Guwahati, Assam'
    ),
    (
        'Assam Higher Secondary Education Council', 
        'ahsec', 
        'The council responsible for regulating, supervising, and developing the system of Higher Secondary Education in the State of Assam.', 
        'https://ahsec.assam.gov.in', 
        'Bamunimaidam, Guwahati, Assam'
    ),
    (
        'Board of Secondary Education, Assam', 
        'seba', 
        'The state-level board of school education responsible for regulating, supervising, and developing secondary education in Assam.', 
        'https://sebaonline.org', 
        'Guwahati, Assam'
    ),
    (
        'Assam Career', 
        'assam-career', 
        'Aggregated news and private/government job portal sourcing opportunities across Northeast India.', 
        'https://www.assamcareer.com', 
        'Assam, India'
    ),
    (
        'Daily Assam Job', 
        'daily-assam-job', 
        'Aggregated job board listing government, banking, and private opportunities in Assam.', 
        'https://www.dailyassamjob.in', 
        'Assam, India'
    ),
    (
        'National Career Service', 
        'ncs-portal', 
        'The National Career Service portal is a mission-mode project under the Ministry of Labour and Employment, Government of India.', 
        'https://www.ncs.gov.in', 
        'New Delhi, India'
    ),
    (
        'Assam University, Silchar', 
        'assam-university', 
        'A Central University established in Silchar, Assam in 1994, offering academic programs across multiple fields in Southern Assam.', 
        'https://www.aus.ac.in', 
        'Silchar, Cachar, Assam'
    ),
    (
        'Assam Science and Technology University', 
        'astu', 
        'A State University established by the Government of Assam to regulate and provide higher education in engineering and technology disciplines.', 
        'https://astu.ac.in', 
        'Jalukbari, Guwahati, Assam'
    ),
    (
        'Gauhati High Court', 
        'gauhati-high-court', 
        'The principal judicial court for the state of Assam, Nagaland, Mizoram, and Arunachal Pradesh, responsible for judicial recruitments.', 
        'https://ghconline.gov.in', 
        'Guwahati, Assam'
    ),
    (
        'AllJobAssam', 
        'all-job-assam', 
        'Aggregated local job board listing public and private sector vacancies across Assam districts.', 
        'https://alljobassam.com', 
        'Assam, India'
    ),
    (
        'Krishna Kanta Handiqui State Open University', 
        'krishna-kanta-handiqui-state-open-university', 
        'Krishna Kanta Handiqui State Open University (KKHSOU) is a state university located in Guwahati, Assam, India. It was established in 2005 as the first open university in Northeast India.', 
        'https://kkhsou.ac.in', 
        'Guwahati, Assam, India'
    ),
    (
        'Assam Women''s University', 
        'assam-womens-university', 
        'Assam Women''s University (AWU) is a state university located in Jorhat, Assam, India. It was established in 2013 by the Government of Assam to promote higher education for women.', 
        'https://awu.ac.in', 
        'Jorhat, Assam, India'
    ),
    (
        'Numaligarh Refinery Limited', 
        'numaligarh-refinery-limited', 
        'Numaligarh Refinery Limited (NRL) is a public sector oil company located in Numaligarh, Golaghat district, Assam, India. It is a subsidiary of Oil India Limited.', 
        'https://www.nrl.co.in', 
        'Numaligarh, Golaghat, Assam'
    ),
    (
        'assamJOBnews', 
        'assamjobnews', 
        'Aggregated local job board and educational news portal sourcing private and public sector opportunities across Assam.', 
        'https://www.assamjobnews.in', 
        'Assam, India'
    ),
    (
        'Gauhati University',
        'gauhati-university',
        'The oldest and largest state university in Northeast India, established in 1948.',
        'https://www.gauhati.ac.in',
        'Jalukbari, Guwahati, Assam'
    ),
    (
        'Cotton University',
        'cotton-university',
        'A premier state university in Guwahati, formerly known as Cotton College, established in 1901.',
        'https://cottonuniversity.ac.in',
        'Guwahati, Assam'
    ),
    (
        'Dibrugarh University',
        'dibrugarh-university',
        'A state university located in Dibrugarh, Assam, established in 1965 to promote higher education in Eastern Assam.',
        'https://dibru.ac.in',
        'Dibrugarh, Assam'
    )
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    website = EXCLUDED.website,
    location = EXCLUDED.location;
