-- SQL Script to Update Notices Table and Create Scraper Runs Table
-- Run this inside your Supabase SQL Editor.

-- 1. Add new columns to notices table
ALTER TABLE notices ADD COLUMN IF NOT EXISTS content_hash TEXT;
ALTER TABLE notices ADD COLUMN IF NOT EXISTS attachment_url TEXT;

-- 2. Populate content_hash for existing records using md5 of title and description
UPDATE notices 
SET content_hash = md5(lower(regexp_replace(title || '|' || COALESCE(description, ''), '\s+', ' ', 'g')))
WHERE content_hash IS NULL;

-- 3. Set content_hash to NOT NULL
ALTER TABLE notices ALTER COLUMN content_hash SET NOT NULL;

-- 4. Add UNIQUE constraint to content_hash
ALTER TABLE notices DROP CONSTRAINT IF EXISTS notices_content_hash_key;
ALTER TABLE notices ADD CONSTRAINT notices_content_hash_key UNIQUE (content_hash);

-- 5. Drop the unique constraint on source_url to support flexible scraping and URLs
ALTER TABLE notices DROP CONSTRAINT IF EXISTS notices_source_url_key;

-- 6. Create the scraper_runs table for run tracking and monitoring
CREATE TABLE IF NOT EXISTS scraper_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scraper_name TEXT NOT NULL,
    status TEXT NOT NULL, -- 'running', 'completed', 'failed'
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    items_scraped INTEGER DEFAULT 0,
    items_inserted INTEGER DEFAULT 0,
    items_updated INTEGER DEFAULT 0,
    errors TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance and monitoring scans
CREATE INDEX IF NOT EXISTS idx_notices_content_hash ON notices(content_hash);
CREATE INDEX IF NOT EXISTS idx_scraper_runs_name ON scraper_runs(scraper_name);
CREATE INDEX IF NOT EXISTS idx_scraper_runs_status ON scraper_runs(status);
