-- Phase 5 Database Update: Create saved_notices table and indices + Seed new institutions

-- 1. Create the saved_notices table linking auth.users and notices
CREATE TABLE IF NOT EXISTS saved_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    notice_id BIGINT NOT NULL REFERENCES notices(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, notice_id)
);

-- 2. Create indexes for performance on joins and user lookups
CREATE INDEX IF NOT EXISTS idx_saved_notices_user_id ON saved_notices(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_notices_notice_id ON saved_notices(notice_id);

-- 3. Seed new institutions for the expanded scrapers list
INSERT INTO institutions (name, slug, description, website, location)
VALUES
    ('Tezpur University', 'tezpur-university', 'A Central University located in Tezpur, Assam, established by an Act of Parliament in 1994.', 'https://www.tezu.ernet.in', 'Tezpur, Sonitpur, Assam'),
    ('Bodoland University', 'bodoland-university', 'A state university located in Kokrajhar, Assam, catering to the higher education needs of the Bodoland Territorial Region.', 'https://www.buniv.edu.in', 'Kokrajhar, Assam'),
    ('Mangaldai College', 'mangaldai-college', 'A premier co-educational higher education institution located in Mangaldai, Darrang, Assam.', 'https://mangaldaicollege.org', 'Mangaldai, Darrang, Assam'),
    ('National Health Mission, Assam', 'nhm-assam', 'The state branch of the National Health Mission, responsible for health systems reinforcement and recruitment in Assam.', 'https://nhm.assam.gov.in', 'Guwahati, Assam'),
    ('Assam Engineering Service Recruitment Board', 'aesrb', 'The board responsible for conducting recruitment examinations for various engineering and technical academic posts in Assam.', 'https://www.aesrb.in', 'Guwahati, Assam'),
    ('Assam Higher Secondary Education Council', 'ahsec', 'The council responsible for regulating, supervising, and developing the system of Higher Secondary Education in the State of Assam.', 'https://ahsec.assam.gov.in', 'Bamunimaidam, Guwahati, Assam'),
    ('Board of Secondary Education, Assam', 'seba', 'The state-level board of school education responsible for regulating, supervising, and developing secondary education in Assam.', 'https://sebaonline.org', 'Guwahati, Assam'),
    ('Assam Career', 'assam-career', 'Aggregated news and private/government job portal sourcing opportunities across Northeast India.', 'https://www.assamcareer.com', 'Assam, India'),
    ('Daily Assam Job', 'daily-assam-job', 'Aggregated job board listing government, banking, and private opportunities in Assam.', 'https://www.dailyassamjob.in', 'Assam, India'),
    ('National Career Service', 'ncs-portal', 'The National Career Service portal is a mission-mode project under the Ministry of Labour and Employment, Government of India.', 'https://www.ncs.gov.in', 'New Delhi, India')
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    website = EXCLUDED.website,
    location = EXCLUDED.location;
