-- Database Schema for AssamStudentHub Scraper notices table.
-- Copy and run this script inside your Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    source TEXT NOT NULL,
    source_url TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL,
    content_type TEXT,
    institution TEXT NOT NULL,
    institution_slug TEXT,
    posted_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    tags TEXT[] DEFAULT '{}',
    slug TEXT NOT NULL UNIQUE,
    raw_html TEXT,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance and scanning
CREATE INDEX IF NOT EXISTS idx_notices_source_url ON notices(source_url);
CREATE INDEX IF NOT EXISTS idx_notices_slug ON notices(slug);
CREATE INDEX IF NOT EXISTS idx_notices_category ON notices(category);
CREATE INDEX IF NOT EXISTS idx_notices_institution ON notices(institution);
CREATE INDEX IF NOT EXISTS idx_notices_is_active ON notices(is_active);
CREATE INDEX IF NOT EXISTS idx_notices_content_type ON notices(content_type);
CREATE INDEX IF NOT EXISTS idx_notices_institution_slug ON notices(institution_slug);
